import { Roboto } from "next/font/google";
import "./globals.css";


const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "700"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  robots: "noindex, nofollow",
  icons: {
    icon: "/frontix_logo.webp"
  }
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
